version: '2.1'

services:
  node-express-mongodb-starter:
    image: node-express-mongodb-starter
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
