version: '2.1'

services:
  node-express-mongodb-starter:
    image: node-express-mongodb-starter
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
